name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - "*"
  release:
    types:
      - published
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        pwd
        mkdir build
        cd build
        cmake .. -DOPTIMIZE_LEVEL="-O2"
        make -j$(nproc)
    - name: CPU Info
      run: |
        pwd
        cp scripts/cpuinfo.sh build
        cd build
        bash cpuinfo.sh cpuinfo.txt
        CPU_INFO=$(cat << EOF
        $(cat cpuinfo.txt)
        EOF
        )
        echo "CPU_INFO<<EOF" >> $GITHUB_ENV
        echo "$CPU_INFO" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Test
      run: |
        pwd
        cd build
        ./csrc/benchmark 300 400 500
        TEST_RESULT=$(cat << EOF
        ## Speed Test
        $(cat speed_test.md)
        EOF
        )
        echo "TEST_RESULT<<EOF" >> $GITHUB_ENV
        echo "$TEST_RESULT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "::set-output name=current::$(TZ=Asia/Shanghai date +"%Y/%m/%d %H:%M.%S")"
      id: speed_test
    - name: Comment ISSUE
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          [Github Actions: ${{ steps.speed_test.outputs.current }}](https://github.com/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ github.run_id }}/)
          ${{ env.CPU_INFO }}
          ${{ env.TEST_RESULT }}
        pr_number: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          [Github Actions: ${{ steps.speed_test.outputs.current }}](https://github.com/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ github.run_id }}/)
          ${{ env.CPU_INFO }}
          ${{ env.TEST_RESULT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
