name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [review_requested]
    branches:
      - "*"
  release:
    types:
      - published
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        pwd
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
    - name: Test
      run: |
        pwd
        cd build
        ./csrc/benchmark 300 400 500
        TEST_RESULT=$(cat << EOF
        $(cat speed_test.md)
        EOF
        )
        echo "TEST_RESULT<<EOF" >> $GITHUB_ENV
        echo "$TEST_RESULT" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        echo "::set-output current=$(TZ=Asia/Shanghai date)"
      id: speed_test
    - name: Comment ISSUE
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          time: ${{ steps.speed_test.outputs.current }}
          id_number_attempt: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          ${{ env.TEST_RESULT }}
        pr_number: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          time: ${{ steps.speed_test.outputs.current }}
          id_number_attempt: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          ${{ env.TEST_RESULT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
